# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

# qBittorrent parameters
qbt:
  host: qbittorrent-vpn-movies:8080
  user: admin
  pass: adminadmin
settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
  - noHL
  - issue
  - cross-seed
directory:
  cross_seed: /data/.torrents/movies/.watchfolder
  root_dir: /data/.torrents/movies
  remote_dir: /data/.torrents/movies
  recycle_bin: /data/.torrents/movies/.RecycleBin
  torrents_dir: /qbit_appdata
  orphaned_dir: /data/.torrents/movies/orphaned_data
cat:
  movies-hd: /data/.torrents/movies/hd
  movies-uhd: /data/.torrents/movies/uhd
  movies: /data/.torrents/movies/
  Radarr-HD.cross-seed: /data/.torrents/movies/hd
  Radarr-UHD.cross-seed: /data/.torrents/movies/uhd
  movies-hd.cross-seed: /data/.torrents/movies/hd
  movies-uhd.cross-seed: /data/.torrents/movies/uhd
  cross-seed: /data/.torrents/movies/cross-seed
cat_change:
  # This moves all the torrents from one category to another category. This executes on --cat-update
  # WARNING: if the paths are different and Default Torrent Management Mode is set to automatic the files could be moved !!!
  # <Old Category Name> : <New Category>
  Radarr-HD.cross-seed: movies-hd
  Radarr-UHD.cross-seed: movies-uhd
  movies-hd.cross-seed: movies-hd
  movies-uhd.cross-seed: movies-uhd
  cross-seed.cross-seed: cross-seed
tracker:
  beyond-hd:
    tag: BHD
  blutopia:
    tag: Blu
  hdts:
    tag: HDT
  passthepopcorn:
    tag: PTP
  privatehd:
    tag: PHD
  torrentleech:
    tag: TL
  reactor:
    tag: FL
  hdbits:
    tag: HDB
  morethantv:
    tag: MTV
  routing.bgp.technology:
    tag: IPT
  tracker.m-team.cc:
    tag: MTTP
  tracker.tleechreload.org:
    tag: TL
  async.empirehost.me:
    tag: IPT
  127.0.0.1.stackoverflow.tech:
    tag: IPT
  skipthetrailers.xyz:
    tag: STT
  www.hawke.uno:
    tag: HUNO
  tracker.revolutiontt.me:
    tag: RTT
  hawke.uno:
    tag: HUNO
  tracker.alpharatio.cc:
    tag: AR
nohardlinks:
- movies-hd
- movies-uhd
- cross-seed
share_limits:
  unlimited-noHL:
    priority: 1
    include_any_tags:
    - BHD
    - Blu
    - PTP
    - HUNO
    - STT
    - RTT
    include_all_tags:
    - noHL
    categories:
    - movies-hd
    - movies-uhd
    - cross-seed
    max_ratio: -1
    max_seeding_time: 28800
    cleanup: true
    add_group_to_tag: false
  unlimited:
    priority: 2
    include_any_tags:
    - BHD
    - Blu
    - PTP
    - HUNO
    - STT
    - RTT
    categories:
    - movies-hd
    - movies-uhd
    - cross-seed
    max_ratio: -1
    max_seeding_time: -1
    limit_upload_speed: -1
    cleanup: true
    add_group_to_tag: false
  limited-noHL:
    priority: 3
    include_any_tags:
    - HDT
    - PHD
    - FL
    - MTTP
    - TL
    - IPT
    include_all_tags:
    - noHL
    categories:
    - movies-hd
    - movies-uhd
    - cross-seed
    max_ratio: 5
    max_seeding_time: 28800
    limit_upload_speed: 1024
    cleanup: true
    add_group_to_tag: false
  limited:
    priority: 4
    include_any_tags:
    - HDT
    - PHD
    - FL
    - MTTP
    - TL
    - IPT
    categories:
    - movies-hd
    - movies-uhd
    - cross-seed
    max_ratio: -1
    max_seeding_time: -1
    limit_upload_speed: 1024
    cleanup: true
    add_group_to_tag: false
recyclebin:
  enabled: true
  empty_after_x_days: 7
  save_torrents: true
  split_by_category: false
orphaned:
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - '**/*.!qB'

  empty_after_x_days:
notifiarr:
  apikey: 27e670d6-aab1-4695-89df-09542a7e6c6d
  instance: Movies
webhooks:
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  function:
    cross_seed: notifiarr
    recheck: notifiarr
    cat_update: notifiarr
    tag_update: notifiarr
    rem_unregistered: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    empty_recyclebin: notifiarr
    tag_tracker_error: notifiarr
    share_limits:
bhd:
  apikey: xxx
